# Generated by Django 6.0.1 on 2026-01-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_assettransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='BTCEUR15m',
            fields=[
                ('timestamp', models.BigIntegerField(help_text='Unix timestamp in milliseconds', primary_key=True, serialize=False)),
                ('open', models.FloatField(help_text='Opening price in EUR')),
                ('high', models.FloatField(help_text='Highest price in period (EUR)')),
                ('low', models.FloatField(help_text='Lowest price in period (EUR)')),
                ('close', models.FloatField(help_text='Closing price in EUR')),
                ('volume', models.FloatField(help_text='Trading volume in BTC')),
                ('datum', models.TextField(help_text='Human-readable datetime (YYYY-MM-DD HH:MM:SS)')),
            ],
            options={
                'verbose_name': 'BTC/EUR 15-Minute Candle',
                'verbose_name_plural': 'BTC/EUR 15-Minute Candles',
                'db_table': 'btc_eur_15m',
                'ordering': ['timestamp'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BTCEUR1d',
            fields=[
                ('timestamp', models.BigIntegerField(help_text='Unix timestamp in milliseconds', primary_key=True, serialize=False)),
                ('open', models.FloatField(help_text='Opening price in EUR')),
                ('high', models.FloatField(help_text='Highest price in period (EUR)')),
                ('low', models.FloatField(help_text='Lowest price in period (EUR)')),
                ('close', models.FloatField(help_text='Closing price in EUR')),
                ('volume', models.FloatField(help_text='Trading volume in BTC')),
                ('datum', models.TextField(help_text='Human-readable datetime (YYYY-MM-DD HH:MM:SS)')),
            ],
            options={
                'verbose_name': 'BTC/EUR 1-Day Candle',
                'verbose_name_plural': 'BTC/EUR 1-Day Candles',
                'db_table': 'btc_eur_1d',
                'ordering': ['timestamp'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BTCEUR1h',
            fields=[
                ('timestamp', models.BigIntegerField(help_text='Unix timestamp in milliseconds', primary_key=True, serialize=False)),
                ('open', models.FloatField(help_text='Opening price in EUR')),
                ('high', models.FloatField(help_text='Highest price in period (EUR)')),
                ('low', models.FloatField(help_text='Lowest price in period (EUR)')),
                ('close', models.FloatField(help_text='Closing price in EUR')),
                ('volume', models.FloatField(help_text='Trading volume in BTC')),
                ('datum', models.TextField(help_text='Human-readable datetime (YYYY-MM-DD HH:MM:SS)')),
            ],
            options={
                'verbose_name': 'BTC/EUR 1-Hour Candle',
                'verbose_name_plural': 'BTC/EUR 1-Hour Candles',
                'db_table': 'btc_eur_1h',
                'ordering': ['timestamp'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BTCEUR4h',
            fields=[
                ('timestamp', models.BigIntegerField(help_text='Unix timestamp in milliseconds', primary_key=True, serialize=False)),
                ('open', models.FloatField(help_text='Opening price in EUR')),
                ('high', models.FloatField(help_text='Highest price in period (EUR)')),
                ('low', models.FloatField(help_text='Lowest price in period (EUR)')),
                ('close', models.FloatField(help_text='Closing price in EUR')),
                ('volume', models.FloatField(help_text='Trading volume in BTC')),
                ('datum', models.TextField(help_text='Human-readable datetime (YYYY-MM-DD HH:MM:SS)')),
            ],
            options={
                'verbose_name': 'BTC/EUR 4-Hour Candle',
                'verbose_name_plural': 'BTC/EUR 4-Hour Candles',
                'db_table': 'btc_eur_4h',
                'ordering': ['timestamp'],
                'abstract': False,
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpenOrder',
            fields=[
                ('order_id', models.CharField(help_text='Binance order ID', max_length=50, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, default='BTC/EUR', help_text='Trading pair symbol', max_length=20)),
                ('timestamp', models.BigIntegerField(db_index=True, help_text='Order creation timestamp (milliseconds)')),
                ('datetime', models.DateTimeField(help_text='Human-readable datetime')),
                ('type', models.CharField(choices=[('limit', 'Limit'), ('market', 'Market'), ('stop_loss', 'Stop Loss'), ('stop_loss_limit', 'Stop Loss Limit')], help_text='Order type', max_length=20)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], db_index=True, help_text='Order side', max_length=4)),
                ('price', models.DecimalField(decimal_places=8, help_text='Limit price', max_digits=20)),
                ('amount', models.DecimalField(decimal_places=8, help_text='Total order amount', max_digits=20)),
                ('filled', models.DecimalField(decimal_places=8, default=0, help_text='Filled amount', max_digits=20)),
                ('remaining', models.DecimalField(decimal_places=8, help_text='Remaining amount to fill', max_digits=20)),
                ('status', models.CharField(default='open', help_text='Order status', max_length=20)),
                ('synced_at', models.DateTimeField(auto_now_add=True, help_text='When this order was synced')),
            ],
            options={
                'verbose_name': 'Open Order',
                'verbose_name_plural': 'Open Orders',
                'db_table': 'open_orders',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OrderBlock1h',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, default='BTC/EUR', help_text='Trading pair symbol', max_length=20)),
                ('direction', models.CharField(choices=[('bullish', 'Bullish'), ('bearish', 'Bearish')], db_index=True, help_text='Bullish (demand) or Bearish (supply)', max_length=8)),
                ('created_ts_ms', models.BigIntegerField(db_index=True, help_text='Timestamp when Order Block candle formed (milliseconds)')),
                ('valid_from_ts_ms', models.BigIntegerField(db_index=True, help_text='Timestamp when Order Block became valid')),
                ('valid_to_ts_ms', models.BigIntegerField(blank=True, help_text='Timestamp when Order Block was invalidated (null if still valid)', null=True)),
                ('price_low', models.DecimalField(decimal_places=8, help_text='Lower bound of Order Block zone (EUR)', max_digits=20)),
                ('price_high', models.DecimalField(decimal_places=8, help_text='Upper bound of Order Block zone (EUR)', max_digits=20)),
                ('atr14', models.DecimalField(decimal_places=8, help_text='ATR(14) value at time of formation', max_digits=20)),
                ('bos_level', models.DecimalField(decimal_places=8, help_text='Break of Structure level that confirmed this Order Block', max_digits=20)),
                ('displacement_range', models.DecimalField(decimal_places=8, help_text='Range of displacement candle (high - low)', max_digits=20)),
                ('status', models.CharField(choices=[('fresh', 'Fresh'), ('touched', 'Touched'), ('invalid', 'Invalid')], db_index=True, default='fresh', help_text='Current status: fresh, touched, or invalid', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created in database')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
            ],
            options={
                'verbose_name': 'Order Block (1h)',
                'verbose_name_plural': 'Order Blocks (1h)',
                'db_table': 'order_blocks_1h',
                'ordering': ['-created_ts_ms'],
            },
        ),
        migrations.RenameIndex(
            model_name='assettransaction',
            new_name='asset_trans_timesta_20ba87_idx',
            old_name='asset_trans_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='assettransaction',
            new_name='asset_trans_transac_04b0f5_idx',
            old_name='asset_trans_type_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='assettransaction',
            new_name='asset_trans_currenc_4824cd_idx',
            old_name='asset_trans_currency_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='assettransaction',
            new_name='asset_trans_status_09e49b_idx',
            old_name='asset_trans_status_idx',
        ),
        migrations.RenameIndex(
            model_name='btceurtrade',
            new_name='btc_eur_tra_timesta_120a06_idx',
            old_name='btc_eur_tra_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='btceurtrade',
            new_name='btc_eur_tra_side_f08dee_idx',
            old_name='btc_eur_tra_side_timesta_idx',
        ),
        migrations.RenameIndex(
            model_name='btceurtrade',
            new_name='btc_eur_tra_datetim_7fa115_idx',
            old_name='btc_eur_tra_datetim_idx',
        ),
        migrations.AddIndex(
            model_name='openorder',
            index=models.Index(fields=['symbol'], name='open_orders_symbol_df1e21_idx'),
        ),
        migrations.AddIndex(
            model_name='openorder',
            index=models.Index(fields=['side'], name='open_orders_side_1eb8ec_idx'),
        ),
        migrations.AddIndex(
            model_name='openorder',
            index=models.Index(fields=['-timestamp'], name='open_orders_timesta_2c267e_idx'),
        ),
        migrations.AddIndex(
            model_name='orderblock1h',
            index=models.Index(fields=['symbol', 'status', '-created_ts_ms'], name='idx_ob_symbol_status_ts'),
        ),
        migrations.AddIndex(
            model_name='orderblock1h',
            index=models.Index(fields=['direction', 'status'], name='idx_ob_direction_status'),
        ),
        migrations.AddIndex(
            model_name='orderblock1h',
            index=models.Index(fields=['valid_from_ts_ms', 'valid_to_ts_ms'], name='idx_ob_valid_time_range'),
        ),
    ]
